FloatLayout:
    Label:
        text: 'OLÁ JOÃO PEDRO!!!'
    Image:
        source: 'images/docs2.png'
        allow_stretch: True
        size_hint: 0.5, 0.6
        pos_hint: {'center_x': 0.75, 'center_y': 0.45}
    Button:
        text: 'CLICA AQUI AMOR!'
        pos_hint: {'center_x': 0.5, 'center_y': 0.42}
        size_hint: 0.2, 0.05
    Button:
        text: 'CLICA AQUI AMOR 2!'
        pos_hint: {'center_x': 0.5, 'center_y': 0.35}
        size_hint: 0.2, 0.05
        